# Use the official 15.1 alpine PostgreSQL image as a base image
FROM postgres:15.1-alpine

# Expose the PostgreSQL port
EXPOSE 5432

# The default command to run when starting the container
CMD ["postgres"]
