{
 "title": "App Performance",
 "description": "Top 5 highest Reviews apps;\nPrice per Category;\nTop 50 most downloaded apps.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "App Performance: Average Price per app in a Category",
   "type": "table",
   "description": "Ordered by Average price in descent so that it is possible to see the average price of apps per category and the total applications that exist in each.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"Category\", \nCONCAT('$', CAST(ROUND(AVG(CASE \n                                  WHEN \"Price\" != '0' THEN CAST(SUBSTRING(\"Price\", 2) AS DECIMAL(10, 2))\n                                  ELSE 0 -- or use NULL if you prefer to exclude these cases from the average\n                              END), 2) AS VARCHAR)) AS \"Average Price\",\ncount(\"App\") as \"Total applications\"\n\nFROM appperformance\nWHERE \n  \"Category\" IS NOT NULL AND \"Category\" != ''\nGROUP BY \"Category\" \nORDER BY 2 Desc"
    }
   ]
  },
  {
   "title": "App Performance: Highest installed Apps",
   "type": "table",
   "description": "Top 50 apps with the highest amount of installs",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"App\" as \"Application Name\", \n    CASE\n        WHEN \"Total_Installs\" >= 1000000000 THEN CONCAT(CAST(\"Total_Installs\" / 1000000000 AS VARCHAR), 'B+')\n        WHEN \"Total_Installs\" >= 1000000 THEN CONCAT(CAST(\"Total_Installs\" / 1000000 AS VARCHAR), 'M+')\n        WHEN \"Total_Installs\" >= 1000 THEN CONCAT(CAST(\"Total_Installs\" / 1000 AS VARCHAR), 'k+')\n        ELSE CAST(\"Total_Installs\" AS VARCHAR)\n    END as \"Total Installs\", \"Total_Reviews\" as \"Total Reviews\"\nFROM appperformance \nORDER BY \"Total_Installs\" DESC \nLIMIT 50"
    }
   ]
  },
  {
   "title": "App Performance: Highest Reviews",
   "type": "barchart",
   "description": "Top 5 apps with the highest reviews ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"App\", CASE\n        WHEN \"Total_Installs\" >= 1000000000 THEN CONCAT(CAST(\"Total_Installs\" / 1000000000 AS VARCHAR), 'B+')\n        WHEN \"Total_Installs\" >= 1000000 THEN CONCAT(CAST(\"Total_Installs\" / 1000000 AS VARCHAR), 'M+')\n        WHEN \"Total_Installs\" >= 1000 THEN CONCAT(CAST(\"Total_Installs\" / 1000 AS VARCHAR), 'k+')\n        ELSE CAST(\"Total_Installs\" AS VARCHAR)\n    END as \"Total Installs\", \"Total_Reviews\" as \"Total Reviews\"\nFROM appperformance \nORDER BY \"Total_Reviews\" DESC \nLIMIT 5"
    }
   ]
  }
 ]
}