{
 "title": "Category Analysis Dashboard",
 "description": "Dashboard with some analysis on Categories",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Applications distribution per Category",
   "type": "table",
   "description": "Total application distribution per Category, ordered by Total application in descent mode",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"Category\", \"Total_Apps\" AS \"Total Application\" \nFROM categoryanalysis\nWHERE \"Category\" IS NOT NULL \nORDER BY \"Total_Apps\" DESC"
    }
   ]
  },
  {
   "title": "Average Rating of apps per Category",
   "type": "table",
   "description": "Average rating of applications per Category",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"Category\", \"Average_Rating\" AS \"Average Rating\" \nFROM categoryanalysis\nwhere \"Category\" IS NOT NULL\nOrder by 2 DESC"
    }
   ]
  },
  {
   "title": "Average Application size per Category",
   "type": "table",
   "description": "Average Application size per Category",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT \"Category\",\n  CASE\n        WHEN \"Average_Size\" >= 1000000 THEN CONCAT(CAST(\"Average_Size\"  / 1000000.0 AS DECIMAL(10, 1)), 'Mb')\n        WHEN \"Average_Size\" >= 1000 THEN CONCAT(CAST(\"Average_Size\"  / 1000 AS DECIMAL(10, 1)), 'Kb')\n        ELSE CAST(\"Average_Size\" AS VARCHAR) || 'b'\n    END as \"Average Size\" \nFROM categoryanalysis \nWHERE \"Category\" IS NOT NULL\nORDER BY \"Average_Size\" DESC"
    }
   ]
  },
  {
   "title": "Average application Price per Category",
   "type": "table",
   "description": "Average application Price per Category",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT \"Category\", CONCAT('$', \"Average_Price\") AS \"Average Price\"\nFROM categoryanalysis \nWhere \"Category\" IS NOT NULL\nORDER BY 2 DESC"
    }
   ]
  }
 ]
}