{
 "title": "Market Trends",
 "description": "Market trends over a period of time regarding apps installed, ratings given and reviews done to applications.",
 "time": { "from": "2015-01-30T00:00:00.000Z", "to": "2018-08-08T00:00:00.000Z" },
 "panels": [
  {
   "title": "Average Rating given to apps per month",
   "type": "timeseries",
   "description": "Average Rating given to applications per month",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"Last_updated\" AS \"Last Updated\", \"Average_Rating\" AS \"Average Rating\" FROM markettrends"
    }
   ]
  },
  {
   "title": "Total installs by Month",
   "type": "timeseries",
   "description": "Total installs by Month in a time period of 3 years",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"Last_updated\" AS \"Last Updated\", \"Total_Installs\" AS \"Total Installs\" FROM markettrends"
    }
   ]
  },
  {
   "title": "Total Reviews per month",
   "type": "timeseries",
   "description": "Total reviews per month in a time period of 3 years and 6 months",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \"Last_updated\" AS \"Last Updated\", \"Total_Reviews\" AS \"Total Reviews\" FROM markettrends"
    }
   ]
  }
 ]
}