{
 "title": "UserSentimentReview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Average Sentiment per Application",
   "type": "table",
   "description": "Average sentiment per application with the total sentiments from reviews for each application",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"App\" AS \"Application Name\", \"Sentiment\" AS \"Average Sentiment\", count AS \"Total Sentiments\" FROM appsentimentdistribution ORDER BY count DESC "
    }
   ]
  },
  {
   "title": "Application name and Application ID",
   "type": "table",
   "description": "Just a table with both app_id and app",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"App_id\" AS \"Application id\", \"App\" AS \"Application name\" FROM appperformance "
    }
   ]
  },
  {
   "title": "User Sentiment distribution",
   "type": "piechart",
   "description": "User Sentiment distribution by type, user reviews.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"Sentiment\", count(*) as \"Total Sentiment Distribution\" FROM appsentimentdistribution GROUP BY \"Sentiment\""
    }
   ]
  },
  {
   "title": "Sentiment polarity and sentiment subjectivity per Application",
   "type": "barchart",
   "description": "Sentiment Polarity typically ranges from -1 to 1. It indicates how positive or negative the sentiment in the text is. \nSentiment Subjectivity typically ranges from 0 to 1 and indicates how much of the text is subjective (opinionated) versus objective (factual).",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \"App_id\" AS \"Application Id\", \"Average_Polarity\" AS \"Average Polarity\", \"Average_Subjectivity\" AS \"Average Subjectivity\" FROM usersentiment LIMIT 50 "
    }
   ]
  }
 ]
}